Repository Godwin254/rac-tuk, pull requests merged in 2022-06, with the labels that each got.

#2 Update README.md file
  README.md
Labels: documentation

#3 set dev branch
  CONTRIBUTING.md
  README.md
Labels: documentation

#5 About us
  .gitIgnore
  CONTRIBUTING.md
  README.md
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/public/manifest.json
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/index.css
  client/src/index.js
  client/src/reportWebVitals.js
  client/src/setupTests.js
  package-lock.json
  package.json
  server/index.js
Labels: good first issue

#9 Restructured project folders, installed react router v6, few fixes, s…
  client/package-lock.json
  client/package.json
  client/src/About.js
  client/src/App.js
  client/src/Navbar.js
  client/src/components/Navbar.css
  client/src/components/Navbar.js
  client/src/index.js
  client/src/pages/About/About.css
  client/src/pages/About/About.js
  package-lock.json
  server/.env
  server/.gitIgnore
  server/configs/dbConfig.js
  server/controllers/advertsController.js
  server/controllers/eventController.js
  server/index.js
  server/package-lock.json
  server/package.json
  server/routes/adverts.js
  server/routes/events.js
Labels: enhancement
